### ISSUE TITLE
[Feature Request]: Error Message if Resource loading failed

### ISSUE THREAD

**Issue by oberpro** [ccmjs/ccm#1]
> "If loading of at least one resource fails, ccm.load will not return a result and the callback will not be called."

As a developer I want to get a response if the loading of a response failed or not.
Currently the callback has only one parameter "result". Maybe there could be two params result and err where i can check if error is null or not. 
Example: https://nodejs.org/api/fs.html#fs_file_paths

**Comment by akless** [comment]
Good point. It's already on my list. Coming soon with next modernisation of ccm.load method. Thanks for report!

**Comment by akless** [comment]
Fixed since _ccm_ v18. Now you have Promises instead of callback and you can catch an error if loading of a resource fails.
