### ISSUE TITLE
Converting error for some attributes

### ISSUE THREAD

**Issue by hbrs** [ccmjs/ccm#3]
If you pass an object to `ccm` which contains a circular, you get the following error:

    ccm.start('myCCMComponent', {attr: objectWithCircular);

    ccm-20.0.0.min.js:1 Uncaught (in promise) TypeError: Converting circular structure to JSON

Here is an explanation for this problem: https://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json

Should this be fixed within `ccm`or before the object is passed to `ccm`?

**Comment by mkaul** [comment]
ccm.helper.stringify() solves this problem

**Comment by hbrs** [comment]
Like this?

    ccm.start(
        'myCCMComponent.js',
        {metamask: ccm.helper.stringify(window['ethereum'])}
    );

I still get this `circular structure to JSON` error.

**Comment by hbrs** [comment]
If you want to reproduce the error: Install the plugin [metamask](https://metamask.io/) in your browser. Then you get the object `window['ethereum']` injected into your browser.

This object I want to pass to my component for better encapsulation (I could also access it directly within the component).

**Comment by akless** [comment]
An _ccm_ instance configuration must be free of circular structures. _ccm_ solves the most common cases of circular structure (window object, node element, ccm instances, ...) automatically. But in this special case of circular object, it seems that this not helps. So you fist have to free the object from circular structures on your own (or as you say: simply access it directly within the component).
